######################################################################
# Automatically generated by qmake (2.01a) lun. déc. 24 00:03:12 2012
######################################################################

TEMPLATE = app
CONFIG +=  debug
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pentamino.h piece.h plateau.h
SOURCES += main.cpp pentamino.cpp piece.cpp plateau.cpp
