######################################################################
# Automatically generated by qmake (2.01a) sam. déc. 22 13:11:14 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pentamino.h plateau.h
SOURCES += main.cpp pentamino.cpp plateau.cpp
