######################################################################
# Automatically generated by qmake (2.01a) ven. déc. 28 20:05:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pentamino.h piece.h plateau.h
SOURCES += main.cpp pentamino.cpp piece.cpp plateau.cpp
